### ISSUE TITLE
Usage of # and SEO

### ISSUE THREAD

**Issue by novasdream** [DevelopersPL/DevAAC#21]
Anyone here have a website with pages using # in google ? My page index only first link.

https://prerender.io/js-seo/angularjs-seo-get-your-site-indexed-and-to-the-top-of-the-search-results/

https://developers.google.com/webmasters/ajax-crawling/docs/specification

**Comment by DSpeichert** [comment]
It is possible to drop /#/ in URLs but that would require more advanced rewrite rules and rarely anybody would know how to set that up.
We can improve that in future.

**Comment by DSpeichert** [comment]
What do you mean?

**Comment by novasdream** [comment]
The big problem is google have another way to handle with sites  based in javascript request..

Check first 2 links.
about _escaped_fragment_ ( in developers.google. ) 

and about prerendered in first link.

**Comment by DSpeichert** [comment]
There s absolutely no reason to do any sort of pre-rendering. Google plays well with Angular routing as-is. Dropping /#/ does not even affect that, it's purely for better looks.

**Comment by novasdream** [comment]
You have any website online with DevAAC indexed pages ?

**Comment by DSpeichert** [comment]
The demo site devots.dondaniello.com should be indexed. I don't have any other.
