### ISSUE TITLE
Character Create.

### ISSUE THREAD

**Issue by Areeks** [DevelopersPL/DevAAC#35]
This script copy smaples when create character ? I have rook sample and script not copy posx posy and posz to character.

**Comment by DSpeichert** [comment]
No, it does not use samples, it creates the character in `players` table itself.

**Comment by Areeks** [comment]
Then i must use default option on table ye ?

04.12.2016 19:21 "Daniel Speichert" <notifications@github.com> napisał(a):

**Comment by DSpeichert** [comment]
It would work. Or you can simply set default values on the model in DevAAC (that involves modifying DevAAC code).
