### ISSUE TITLE
Error: [$resource:badcfg] when logged in

### ISSUE THREAD

**Issue by bpawel10** [DevelopersPL/DevAAC#36]
When I'm logged out everything works fine, but when I login and refresh the website, API stops working properly and I'm getting this error: `Error: [$resource:badcfg] http://errors.angularjs.org/1.2.18/$resource/badcfg?p0=array&p1=object`.
Once I logout, API immediately starts working again, even without refreshing the page.

There are no errors in nginx error log file.
I'm using nginx 1.4.6 with php 7.1.9.

**Comment by DSpeichert** [comment]
Could not reproduce the issue. Try here: http://164.132.112.176/

**Comment by bpawel10** [comment]
Can you give me login and password?

**Comment by bpawel10** [comment]
What's more, I also tried to configure DevAAC using [otshosting-provisioning](https://github.com/DevelopersPL/otshosting-provisioning/blob/master/templates/nginx-vhost.conf), but it has some issues with routing - when I refresh any page other than index, I'm getting 404. This also happens in the DevAAC instance provided by you - [http://164.132.112.176/](url).

So I think the nginx vhost configuration in otshosting-provisioning repo needs to be fixed, but also the one in DevAAC wiki should be updated.

**Comment by DSpeichert** [comment]
otshosting-provisioning does not install the proper nginx config that is necessary (https://github.com/DevelopersPL/DevAAC/wiki/nginx)
